#!/usr/bin/env python3
"""Generate assets/js/counts.js — the SINGLE SOURCE of content counts, derived from the data.

Run after any change to docs/questions/*.txt, docs/concepts/concepts.txt or docs/acronyms/acronyms.txt.
validate.py calls this at the end, so running the linter already keeps everything in sync.
"""
import json
import glob
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _count_jsonl(path):
    """Return the number of non-empty (record) lines in a JSONL file."""
    n = 0
    for line in open(path, encoding='utf-8'):
        if line.strip():
            n += 1
    return n


def compute():
    """Compute the content counts: totals plus the per-domain question breakdown."""
    by_domain = {}
    q_total = 0
    for f in sorted(glob.glob(os.path.join(BASE, 'docs', 'questions', '*.txt'))):
        domain = os.path.basename(f)[:-4]  # "1.0.txt" -> "1.0"
        c = 0
        for line in open(f, encoding='utf-8'):
            line = line.strip()
            if not line:
                continue
            try:
                json.loads(line)
            except ValueError:
                continue
            c += 1
        by_domain[domain] = c
        q_total += c
    concepts = _count_jsonl(os.path.join(BASE, 'docs', 'concepts', 'concepts.txt'))
    acronyms = _count_jsonl(os.path.join(BASE, 'docs', 'acronyms', 'acronyms.txt'))
    return {'questions': q_total, 'concepts': concepts, 'acronyms': acronyms, 'byDomain': by_domain}


def write(counts):
    """Write assets/js/counts.js from the computed counts; return the output path."""
    out = os.path.join(BASE, 'docs', 'assets', 'js', 'counts.js')
    banner = ('/* GENERATED by gen_counts.py — do NOT edit by hand.\n'
              '   Single source of content counts; regenerate by running validate.py. */\n')
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write(banner + 'window.SECPLUS_COUNTS = ' + json.dumps(counts, ensure_ascii=False) + ';\n')
    return out


if __name__ == '__main__':
    c = compute()
    p = write(c)
    print('generated ' + p + ': ' + json.dumps(c, ensure_ascii=False))
